### ISSUE TITLE
SEL and CLR

### ISSUE THREAD

**Issue by Jumpingmanjim** [dshadoff/PCE_Controller_Info#1]
Hello

Can I please make a suggestion, the terms SEL and CLR are used a lot in the document but the meaning of SEL and CLR aren't explained until much later in the document. Maybe if they were explained at the top of the page it would be easier to understand.

**Comment by dshadoff** [comment]
I was planning to do this when I started writing the document, but couldn't think of any way to do so without raising more questions and causing more confusion.  For example, CLR has no relevance until the multitap stage, and SEL's purpose is obvious with the first controller.

I continue to add to this document, and will take another look at whether this can be done effectively.

**Comment by Jumpingmanjim** [comment]
Ok sounds good thanks.

**Comment by dshadoff** [comment]
I have added a brief description at the top.

**Comment by Jumpingmanjim** [comment]
awesome thanks
